{{- if .Values.persistentVolume.enabled -}}
{{- if not .Values.persistentVolume.existingClaim -}}
{{- if not .Values.statefulSet.enabled -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trickster.fullname" . }}
{{- if .Values.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.persistentVolume.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "trickster.labels" . | nindent 4 }}
    {{- if .Values.persistentVolume.labels }}
    {{- toYaml .Values.persistentVolume.labels | nindent 4 }}
    {{- end }}
spec:
  {{- include "trickster.pvcSpec" . | nindent 2 }}
{{- end -}}
{{- end -}}
{{- end -}}
