{{- if .Values.persistentVolume.enabled -}}
{{- if not .Values.persistentVolume.existingClaim -}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "trickster.fullname" . }}
{{- if .Values.persistentVolume.annotations }}
  annotations:
{{ toYaml .Values.persistentVolume.annotations | indent 4 }}
{{- end }}
  labels:
    {{- include "trickster.labels" . | nindent 4 }}
    {{- if .Values.persistentVolume.labels }}
    {{- toYaml .Values.persistentVolume.labels | nindent 4 }}
    {{- end }}
spec:
  accessModes:
{{ toYaml .Values.persistentVolume.accessModes | indent 4 }}
{{- if .Values.persistentVolume.storageClass }}
{{- if (eq "-" .Values.persistentVolume.storageClass) }}
  storageClassName: ""
{{- else }}
  storageClassName: "{{ .Values.persistentVolume.storageClass }}"
{{- end }}
{{- end }}
  resources:
    requests:
      storage: "{{ .Values.persistentVolume.size }}"
{{- if .Values.persistentVolume.selector }}
  selector:
    {{- toYaml .Values.persistentVolume.selector | nindent 4 }}
{{- end }}
{{- if .Values.persistentVolume.volumeName }}
  volumeName: "{{ .Values.persistentVolume.volumeName }}"
{{- end }}
{{- end -}}
{{- end -}}